// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDznnn9dxs0mb-i9JRrFicLuO9LEvSFx-I',
    appId: '1:923321843822:web:274fba517a3a2a2680e67f',
    messagingSenderId: '923321843822',
    projectId: 'lionsapp-973b3',
    authDomain: 'lionsapp-973b3.firebaseapp.com',
    databaseURL: 'https://lionsapp-973b3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lionsapp-973b3.appspot.com',
    measurementId: 'G-97Q64ZFCE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK3jiaInoOq5NqipMNVujttL0VJr7DcKw',
    appId: '1:923321843822:android:e238895b700aaf2180e67f',
    messagingSenderId: '923321843822',
    projectId: 'lionsapp-973b3',
    databaseURL: 'https://lionsapp-973b3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lionsapp-973b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq1OuwtkjBsxRXCj99X21QcMSQoGL86Ko',
    appId: '1:923321843822:ios:d14efb69a86721d980e67f',
    messagingSenderId: '923321843822',
    projectId: 'lionsapp-973b3',
    databaseURL: 'https://lionsapp-973b3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lionsapp-973b3.appspot.com',
    iosClientId: '923321843822-umugp2ao5slagojhm06hc7ig1iteg8ks.apps.googleusercontent.com',
    iosBundleId: 'com.teamlion.lionsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq1OuwtkjBsxRXCj99X21QcMSQoGL86Ko',
    appId: '1:923321843822:ios:d14efb69a86721d980e67f',
    messagingSenderId: '923321843822',
    projectId: 'lionsapp-973b3',
    databaseURL: 'https://lionsapp-973b3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lionsapp-973b3.appspot.com',
    iosClientId: '923321843822-umugp2ao5slagojhm06hc7ig1iteg8ks.apps.googleusercontent.com',
    iosBundleId: 'com.teamlion.lionsapp',
  );
}
