//Licensed under the EUPL v.1.2 or later
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsO3xPQO2mtUDiMmlji5rJNaK6CaRzUfM',
    appId: '1:1059713907643:web:ce4f7a47365ca05912e29e',
    messagingSenderId: '1059713907643',
    projectId: 'serviceclub-app',
    authDomain: 'serviceclub-app.firebaseapp.com',
    databaseURL: 'https://serviceclub-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'serviceclub-app.appspot.com',
    measurementId: 'G-PSPRWVVBK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrFwt_jb2GjnN8cT_Hhj5T_QMjdjY47p4',
    appId: '1:1059713907643:android:585c721d6a68fd2d12e29e',
    messagingSenderId: '1059713907643',
    projectId: 'serviceclub-app',
    databaseURL: 'https://serviceclub-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'serviceclub-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7dYP92wsByiIvKl5P-i4whLPomc_Zdrw',
    appId: '1:1059713907643:ios:0e24b289b78af12912e29e',
    messagingSenderId: '1059713907643',
    projectId: 'serviceclub-app',
    databaseURL: 'https://serviceclub-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'serviceclub-app.appspot.com',
    androidClientId: '1059713907643-2dkp8pkilvd3piv8n3m13f3mj9ms12jh.apps.googleusercontent.com',
    iosClientId: '1059713907643-er5mbrgdt1ilheqgf3qlslkb9t7mau9m.apps.googleusercontent.com',
    iosBundleId: 'com.serviceclub-app.lionsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7dYP92wsByiIvKl5P-i4whLPomc_Zdrw',
    appId: '1:1059713907643:ios:77e120ca9948dab712e29e',
    messagingSenderId: '1059713907643',
    projectId: 'serviceclub-app',
    databaseURL: 'https://serviceclub-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'serviceclub-app.appspot.com',
    androidClientId: '1059713907643-2dkp8pkilvd3piv8n3m13f3mj9ms12jh.apps.googleusercontent.com',
    iosClientId: '1059713907643-02eu7n5sdqsc2h2eov2skfmf1va38mqv.apps.googleusercontent.com',
    iosBundleId: 'com.serviceclubapp.spendenapp',
  );
}
