// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsO3xPQO2mtUDiMmlji5rJNaK6CaRzUfM',
    appId: '1:1059713907643:web:ce4f7a47365ca05912e29e',
    messagingSenderId: '1059713907643',
    projectId: 'serviceclub-app',
    authDomain: 'serviceclub-app.firebaseapp.com',
    databaseURL: 'https://serviceclub-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'serviceclub-app.appspot.com',
    measurementId: 'G-PSPRWVVBK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsO3xPQO2mtUDiMmlji5rJNaK6CaRzUfM',
    appId: '1:1059713907643:web:ce4f7a47365ca05912e29e',
    messagingSenderId: '1059713907643',
    projectId: 'serviceclub-app',
    databaseURL: 'https://serviceclub-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'serviceclub-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsO3xPQO2mtUDiMmlji5rJNaK6CaRzUfM',
    appId: '1:1059713907643:web:ce4f7a47365ca05912e29e',
    messagingSenderId: '1059713907643',
    projectId: 'serviceclub-app',
    databaseURL: 'https://serviceclub-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'serviceclub-app.appspot.com',
    iosClientId: '1059713907643-kaaru3jfq7geaqce3sh55nlme6f4ggg9.apps.googleusercontent.com',
    iosBundleId: 'de.serviceclub-app.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsO3xPQO2mtUDiMmlji5rJNaK6CaRzUfM',
    appId: '1:1059713907643:web:ce4f7a47365ca05912e29e',
    messagingSenderId: '1059713907643',
    projectId: 'serviceclub-app',
    databaseURL: 'https://serviceclub-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'serviceclub-app.appspot.com',
    iosClientId: '1059713907643-kaaru3jfq7geaqce3sh55nlme6f4ggg9.apps.googleusercontent.com',
    iosBundleId: 'de.serviceclub-app.app',
  );
}
